/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package eu.MrSnowflake.android.gravityringer;

public final class R {
    public static final class anim {
        public static final int cycle_7=0x7f040000;
        public static final int shake=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int activateServiceBtn=0x7f06000b;
        public static final int btnNoisyThreshold=0x7f060008;
        public static final int btnSilenceThreshold=0x7f060005;
        public static final int chkAutoStart=0x7f060009;
        public static final int chkKeyLock=0x7f06000a;
        public static final int deactivateServiceBtn=0x7f06000c;
        public static final int layMain=0x7f060000;
        public static final int lblDelay=0x7f060001;
        public static final int lblNoisyThreshold=0x7f060006;
        public static final int lblSilenceThreshold=0x7f060003;
        public static final int txtDelay=0x7f060002;
        public static final int txtNoisyThreshold=0x7f060007;
        public static final int txtSilenceThreshold=0x7f060004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int activate_service=0x7f050001;
        public static final int alert_values_btn_back=0x7f05000f;
        public static final int alert_values_btn_edit=0x7f05000e;
        public static final int alert_values_message=0x7f05000d;
        /**  Dialog boxes 
         */
        public static final int alert_values_title=0x7f05000c;
        public static final int app_name=0x7f050000;
        public static final int autostart=0x7f050009;
        public static final int deactivate_service=0x7f050002;
        public static final int delay=0x7f050003;
        /**  Error messages 
         */
        public static final int error_values_not_integer=0x7f050010;
        public static final int error_values_not_number=0x7f050011;
        public static final int keylock=0x7f050008;
        public static final int noisy_treshold=0x7f050006;
        public static final int noisy_treshold_button=0x7f050007;
        public static final int service_started=0x7f05000a;
        public static final int service_stopped=0x7f05000b;
        public static final int silence_treshold=0x7f050004;
        public static final int silence_treshold_button=0x7f050005;
    }
}
